// Code generated by bpf2go; DO NOT EDIT.

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type FilterBpfLpmTrieKeyV4 struct {
	_         structs.HostLayout
	Prefixlen uint32
	Data      [4]uint8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	FilterMapEventsRingbuf    = "events_ringbuf"
	FilterMapRouteLpmMap      = "route_lpm_map"
	FilterProgTcGatewayFilter = "tc_gateway_filter"
)

// LoadFilter returns the embedded CollectionSpec for Filter.
func LoadFilter() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FilterBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Filter: %w", err)
	}

	return spec, err
}

// LoadFilterObjects loads Filter and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*FilterObjects
//	*FilterPrograms
//	*FilterMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadFilterObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadFilter()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// FilterSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FilterSpecs struct {
	FilterProgramSpecs
	FilterMapSpecs
	FilterVariableSpecs
}

// FilterProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FilterProgramSpecs struct {
	TcGatewayFilter *ebpf.ProgramSpec `ebpf:"tc_gateway_filter"`
}

// FilterMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FilterMapSpecs struct {
	EventsRingbuf *ebpf.MapSpec `ebpf:"events_ringbuf"`
	RouteLpmMap   *ebpf.MapSpec `ebpf:"route_lpm_map"`
}

// FilterVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FilterVariableSpecs struct {
}

// FilterObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadFilterObjects or ebpf.CollectionSpec.LoadAndAssign.
type FilterObjects struct {
	FilterPrograms
	FilterMaps
	FilterVariables
}

func (o *FilterObjects) Close() error {
	return _FilterClose(
		&o.FilterPrograms,
		&o.FilterMaps,
	)
}

// FilterMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadFilterObjects or ebpf.CollectionSpec.LoadAndAssign.
type FilterMaps struct {
	EventsRingbuf *ebpf.Map `ebpf:"events_ringbuf"`
	RouteLpmMap   *ebpf.Map `ebpf:"route_lpm_map"`
}

func (m *FilterMaps) Close() error {
	return _FilterClose(
		m.EventsRingbuf,
		m.RouteLpmMap,
	)
}

// FilterVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadFilterObjects or ebpf.CollectionSpec.LoadAndAssign.
type FilterVariables struct {
}

// FilterPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadFilterObjects or ebpf.CollectionSpec.LoadAndAssign.
type FilterPrograms struct {
	TcGatewayFilter *ebpf.Program `ebpf:"tc_gateway_filter"`
}

func (p *FilterPrograms) Close() error {
	return _FilterClose(
		p.TcGatewayFilter,
	)
}

func _FilterClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed filter_bpf.o
var _FilterBytes []byte
